In [1]:
print('Hello')

Hello


In [2]:
8+1

9

In [3]:
pip install tensorflow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 601.4/601.4 MB 7.1 MB/s eta 0:00:00m eta 0:00:010:00:03
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 6.4 MB/s eta 0:00:00 MB/s eta 0:00:01:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 7.9 MB/s eta 0:00:008.2 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 7.1 MB/s eta 0:00:00m eta 0:00:010:01:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 7.3 MB/s eta 0:00:00 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 6.8 MB/s eta 0:00:000:00:01m eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 7.6 MB/s eta 0:00:00 MB/s eta 0:00:01:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 6.9 MB/s eta 0:00:00 MB/s eta 0:00:01:01
Note: you may need to restart the kernel to use updated packages.


In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

2024-10-07 16:03:39.158579: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-10-07 16:03:39.172394: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-07 16:03:39.184373: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-07 16:03:39.188097: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-07 16:03:39.197101: I tensorflow/core/platform/cpu_feature_guar

TensorFlow version: 2.17.0


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/home/afivan/Apps/miniconda/envs/mlt/lib/python3.12/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
I0000 00:00:1728309919.979175  148380 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-10-07 16:05:20.028954: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2343] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering 

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.03379923,  0.80677235, -0.49909717, -0.23380531, -0.163656  ,
        -0.05320639, -0.45325482, -0.32677963, -0.4165551 ,  0.15016097]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.10090047, 0.23385617, 0.06336024, 0.08260982, 0.08861295,
        0.09896116, 0.06633244, 0.07527547, 0.06881204, 0.12127914]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.3130276

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8585 - loss: 0.4870
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9540 - loss: 0.1556
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9657 - loss: 0.1124
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9738 - loss: 0.0854
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9761 - loss: 0.0739


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 640us/step - accuracy: 0.9769 - loss: 0.0743


[0.0742601826786995, 0.9768999814987183]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.2012238e-07, 9.1830925e-09, 3.5527178e-06, 6.5594191e-05,
        4.9373825e-12, 1.7258817e-07, 2.6907031e-12, 9.9992895e-01,
        2.1751123e-07, 1.2608032e-06],
       [1.2274545e-07, 8.6509064e-04, 9.9728239e-01, 1.1051638e-03,
        1.5485956e-14, 7.2985428e-04, 7.8469958e-07, 5.2651572e-10,
        1.6579876e-05, 2.4485561e-12],
       [1.5541028e-07, 9.9961770e-01, 7.2129296e-05, 3.0351123e-06,
        2.4480662e-05, 8.8034194e-06, 4.2436263e-06, 2.4854689e-04,
        2.0416162e-05, 4.5746756e-07],
       [9.9985421e-01, 1.9313944e-08, 3.3908436e-06, 2.0117541e-06,
        2.0715785e-07, 3.8532118e-05, 5.6831919e-05, 3.4724751e-05,
        5.0987592e-07, 9.5444739e-06],
       [7.0509286e-06, 7.6699056e-09, 3.9293650e-06, 6.3844556e-07,
        9.9427265e-01, 6.8882827e-08, 2.2993036e-06, 8.9081659e-05,
        3.0239909e-05, 5.5939094e-03]], dtype=float32)>